version: "3"
services:
  coolguys:
    build:
      context: .
    ports:
      - "3000:3000"
    volumes:
      - ./.output:/.output
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    restart: always
